### ISSUE TITLE
Remove NAs on specific columns only

### ISSUE THREAD

**Issue by vviers** [signaux-faibles/predictsignauxfaibles#14]
Right now, `SFModel._remove_na()` drops observations with _any_ NA value. This is not correct as some NAs are acceptable for some values (e.g. `time_til_outcome`).

Option 1:
define a `DROP_IF_NA` list of fields in config and only drop those observations

Option 2:
Use another default value for `time_til_outcome`(e.g. `False` if outcome has not happened)

WDYT ?

**Comment by vviers** [comment]
Pour info, je préfère grandement l'option 1 mais à la place de `DROP_IF_NA` (qui consiste a lister les champs qui doivent absolument être remplis), je ferais plutot `IGNORE_NA` --> on whiteliste les champs qui ont le droit d'être vides ; le défaut reste de dropper les NA

**Comment by slebastard** [comment]
Je propose effectivement qu'on adopte l'option 1 avec une whitelist.
On aura la partition des champs suivante, en fonction du contenu de config.py:

- les champs pour lesquels une valeur par défaut sera retenue, déclarés dans le dict DEFAULT_DATA_VALUES
- les champs pour lesquels des NA ne résulteront pas dans le retrait du record, déclarés dans la liste IGNORE_NA
- les champs pour lesquels des NA résulteront dans le retrait du record, ie l'intégralité des autres champs

**Comment by vviers** [comment]
Très bien yes

Il faut du coup bien émettre des logs (`logging.info()`) pour prévenir l'utilisateur de ce qui est drop et pourquoi :)
