### ISSUE TITLE
Choose whether random functions should be deterministic

### ISSUE THREAD

**Issue by vviers** [signaux-faibles/predictsignauxfaibles#18]
### Requirement
Set an environment variable `RANDOM_DETERMINISTIC=True` that make all random functions predictable --> this will be useful when using random functions in a notebook environment

### Suggested implementation
- write a python decorator `is_random` to mark all random functions in the codebase
- this decorator will [1] look for the `RANDOM_DETERMINISTIC` environment variable and [2] prepend a `random.seed(42)` before the function if set to True

**Comment by vviers** [comment]
@JazzyPierrot ça t'irait comme implémentation ?

**Comment by pierrecamilleri** [comment]
Oui très bien
