### ISSUE TITLE
pip install fails in virtualenv

### ISSUE THREAD

**Issue by vviers** [signaux-faibles/predictsignauxfaibles#20]
## Reproduce
On the server:

This works :
```sh
pip3 --proxy <your_proxy> install pandas
```

This does not work :
```sh
python3 -m venv .venv
source .venv/bin/activate
pip3 --proxy <your_proxy> install pandas
```
Error :
```
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting pandas
  Could not fetch URL https://pypi.python.org/simple/pandas/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available. - skipping
  Could not find a version that satisfies the requirement pandas (from versions: )
No matching distribution found for pandas
```

## Reason
`openssl` is not found by python when used from within a virtualenv...

**Comment by vviers** [comment]
@slebastard found a "hack" to make this work 💯 . Could you please document it here ? 🙏🏼

**Comment by slebastard** [comment]
The most maintainable solution will be to have a minimal common pool of packages at /usr/local/lib/python3.6/site-packages, and carry these packages to your virtualenv with: `python3 -m venv --system-site-packages path_to_env/my_venv`
This will copy socks.py from common site-packages, which in turn allows to install packages from outside, given that socks5 proxy is declared in ~/.config/pip/pip.conf

Will update gollum doc accordingly!

**Comment by slebastard** [comment]
Updated gollum documentation
