### ISSUE TITLE
Oversample Firms with default

### ISSUE THREAD

**Issue by vviers** [signaux-faibles/predictsignauxfaibles#22]
## Requirement
- As a data scientist, I can pass a `proportion_default` argument to `SFDataset` that controls the proportion of firms in default in the sample
- n_firms_default = `max(proportion_default * sample_size, number_of_defaults)` + warning

## Implementation
MongoDB Aggregation pipeline

**Comment by lcrmorin** [comment]
2 small questions : 

- Do we agree that it also oversample the default in the test set ?
- Any reasons you favored ovsersampling against using weights in the model calibration ?

**Comment by vviers** [comment]
> * Do we agree that it also oversample the default in the test set ?

yes  — you can use `OversampledSFDataset` to create any set (training or otherwise) that you like :) 

> * Any reasons you favored ovsersampling against using weights in the model calibration ?

i'm guessing it just seemed simpler to implement in the short term 🙃 but both approaches are valid in my opinion !

Generally speaking, this functionality is just a small tool to make data scientists' lives easier during exploration and development — but I wouldn't necessarily be comfortable using it in production
