### ISSUE TITLE
Ignore public sector in our model

### ISSUE THREAD

**Issue by vviers** [signaux-faibles/predictsignauxfaibles#31]
## Problem
During one of our discussions with Altarès, they rightfully pointed out that our sample is composed of french _administrations_ or public structures which are at a very low (if not null) risk of defaulting. This could be biasing our model !

## Proposed solution
Drop the following `code_naf`:
- `O` : Administration Publique
- `P`: Enseignement

**Comment by vviers** [comment]
Statistics :
<img width="956" alt="Screenshot 2021-03-02 at 11 53 06" src="https://user-images.githubusercontent.com/30295971/109638142-ecc58d00-7b4d-11eb-9bec-5c89be15e111.png">

**Comment by slebastard** [comment]
I would advocate for having an optional argument to SFDataset "discard_public" (or "discard_public_nafs" or whatever else) which defaults to True. What do you think?
Once you approve on solution design I can take care of it.

**Comment by vviers** [comment]
Implemented in preprocessing module
