### ISSUE TITLE
MongoDB : Filter on random_order differently

### ISSUE THREAD

**Issue by vviers** [signaux-faibles/predictsignauxfaibles#35]
## What we do now
```js
{'$sort': {'value.random_order': -1}},
{'$limit': 160000}
 ```
 
 ## What we could do
 
 (Assuming there are at least 160000 lines with `random_order in [0.1, 0.2]`)
 
 ```js
{'$match': {'value.random_order': {'$gte': 0.1, '$lt': 0.2}},
{'$limit': 160000}
 ```

## Why
This would allow us to query different partitions of the database while keeping the same arguments in `SFDataset`, e.g. for building train and validate sets

**Comment by pierrecamilleri** [comment]
Not sure to understand the aim here ; random_order is defined for each (SIRET x PERIOD), so the created partitions would not separate different SIRETS, which goes against the constraints set on train and validation sets. 

In addition, the "random_order" variable has initially been created to have deterministic and reproducible sampling from the database, and it looks like your proposition would lose this property (an additional "$sort" stage could be used).

**Comment by vviers** [comment]
The idea is that we want to be able to run :
```python
train = SFDataset(fields = fields, sample_size = 100_000, from = "2016-01", to = "2016-12")
validate = SFDataset(fields = fields, sample_size = 100_000, from = "2016-01", to = "2016-12")
```
and have `train` and `validate` be different dataset

I don't think we can do this as of now ?


### Edit

Granted, we could then do something like
```python
full_data = SFDataset(fields = fields, sample_size = 200_000, from = "2016-01", to = "2016-12")
train, validate = split_train_validate(full_data)
```
which is probably cleaner :)

**Comment by vviers** [comment]
MongoDB perf is now great (10min for 1M lines) 🙂
