### ISSUE TITLE
Filter on categorical variables

### ISSUE THREAD

**Issue by slebastard** [signaux-faibles/predictsignauxfaibles#39]
As a data scientist working on SF, I would like to be able to allocate a SFDataSet specific to a "région" (region), set of "regions", to a "département" (county) or set of "départements".
I propose that we add filters on our MongoDB requests specific to those categoric fields. This may be contingent on adding "région" and "département" as indexes in MongoDB database (@vviers please correct me on this if necessary).
What do you think?

**Comment by lcrmorin** [comment]
As a data scientist you will probably need a versatile way to request "secteur" (industries) too. Maybe the solution here should not be limited to geographical fields, but extended categorical ones.

**Comment by vviers** [comment]
Adding these fields to an index will definitely speed up your queries — but at the cost of creating new indices in MongoDB (they each weight several GBs)

It's a great idea for oft-used filters but we should be careful to keep the number of indices somewhat small 🙂

**Comment by vviers** [comment]
ping @adrienjoly

**Comment by slebastard** [comment]
@lcrmorin I agree. We could add an optional dictionary argument `categories_filter` to the SFDataset constructor, and adapt the query to MongoDB accordingly.

For instance, to query companies in industrial and energy production sectors from any of three specific regions (AND condition between `regions` and `code_naf`:
```
my_cat_filter = {
    "regions": ["Île-de-France", "Auverge Rhônes-Alpes", "Centre Val-de-Loire"],
    "code_naf": ["C", "D", "E"]
}

my_dataset = SFDataset(  
    date_min = "2016-01-01",
    date_max = "2017-01-01",
    sample_size = 1e5,
    categories_filter = my_cat_filter
)
```
Actually, `categories_filter` could even be replaced with a list of dictionaries `categories_filters` so that a dictionary implements an AND condition within its fields, and we query an OR condition between all dictionaries. However this may be a bit too complex and I'm not sure that we'll need this short-term. @vviers WDYT?

**Comment by vviers** [comment]
> @lcrmorin I agree. We could add an optional dictionary argument `categories_filter` to the SFDataset constructor, and adapt the query to MongoDB accordingly.

Instead of passing a dictionary directly, let's try and make use of [`**kwargs`](https://realpython.com/python-kwargs-and-args/#using-the-python-kwargs-variable-in-function-definitions) if we can, that would be cleaner 🙂  

Ideally, we would warn the user if they asked for a filter that cannot be performed efficiently by MongoDB. So I would go for something like :
```python
def __init__(self, date_min, date_max, ..., **kwargs):
    '''
    **kwargs can be any additional `in` or `=` filter you like in the form `mongo_field = [a, b, c]`
    '''
    if **kwargs not None: # or something like this
        logging.warning("Query might not be using indices efficiently when additional filters are provided")
    # your function :) 
```

> Actually, `categories_filter` could even be replaced with a list of dictionaries `categories_filters` so that a dictionary implements an AND condition within its fields, and we query an OR condition between all dictionaries. However this may be a bit too complex and I'm not sure that we'll need this short-term. @vviers WDYT?

Let's stay away from "OR" conditions for now if that's not absolutely needed — we saw with @adrienjoly yesterday that this could lead to sub-optimal queries.

**Comment by vviers** [comment]
Done in #42
